# Generated by Django 3.1.12 on 2025-02-22 17:30

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(storage=djongo.storage.GridFSStorage(base_url='/media/myfiles/', collection='myfiles'), upload_to='pdfs')),
            ],
        ),
    ]
