# Generated by Django 3.1.12 on 2025-02-22 19:39

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(storage=djongo.storage.GridFSStorage(base_url='/media/myfiles/', collection='myfiles'), upload_to='pdfs')),
                ('file_id', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoMetadata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(storage=djongo.storage.GridFSStorage(base_url='/media/myfiles/', collection='myfiles'), upload_to='pdfs')),
                ('title', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('file_id', models.CharField(max_length=24, unique=True)),
            ],
        ),
    ]
