# Generated by Django 3.1.12 on 2025-02-22 03:45

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=djongo.storage.GridFSStorage(base_url='/media/myfiles/', collection='myfiles'), upload_to='pdfs')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
