# Generated by Django 5.1.6 on 2025-02-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250222_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
